# Generated by Django 4.1.7 on 2023-03-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_options_shop_create_at_shop_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
